package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FixturesMatchResult generated by hbm2java
 */
@Entity
@Table(name="fixtures_match_result"
    ,catalog="footballsite"
)
public class FixturesMatchResult  implements java.io.Serializable {


     private Integer recordId;
     private Integer fixturesId;
     private Integer goalsHomeTeam;
     private Integer goalsAwayTeam;

    public FixturesMatchResult() {
    }

    public FixturesMatchResult(Integer fixturesId, Integer goalsHomeTeam, Integer goalsAwayTeam) {
       this.fixturesId = fixturesId;
       this.goalsHomeTeam = goalsHomeTeam;
       this.goalsAwayTeam = goalsAwayTeam;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="fixtures_id")
    public Integer getFixturesId() {
        return this.fixturesId;
    }
    
    public void setFixturesId(Integer fixturesId) {
        this.fixturesId = fixturesId;
    }

    
    @Column(name="goalsHomeTeam")
    public Integer getGoalsHomeTeam() {
        return this.goalsHomeTeam;
    }
    
    public void setGoalsHomeTeam(Integer goalsHomeTeam) {
        this.goalsHomeTeam = goalsHomeTeam;
    }

    
    @Column(name="goalsAwayTeam")
    public Integer getGoalsAwayTeam() {
        return this.goalsAwayTeam;
    }
    
    public void setGoalsAwayTeam(Integer goalsAwayTeam) {
        this.goalsAwayTeam = goalsAwayTeam;
    }




}


