package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FixturesTeam generated by hbm2java
 */
@Entity
@Table(name="fixtures_team"
    ,catalog="footballsite"
)
public class FixturesTeam  implements java.io.Serializable {


     private Integer recordId;
     private Integer teamId;
     private Date date;
     private String status;
     private Integer matchday;
     private String homeTeamName;
     private String awayTeamName;

    public FixturesTeam() {
    }

    public FixturesTeam(Integer teamId, Date date, String status, Integer matchday, String homeTeamName, String awayTeamName) {
       this.teamId = teamId;
       this.date = date;
       this.status = status;
       this.matchday = matchday;
       this.homeTeamName = homeTeamName;
       this.awayTeamName = awayTeamName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="team_id")
    public Integer getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="matchday")
    public Integer getMatchday() {
        return this.matchday;
    }
    
    public void setMatchday(Integer matchday) {
        this.matchday = matchday;
    }

    
    @Column(name="homeTeamName", length=100)
    public String getHomeTeamName() {
        return this.homeTeamName;
    }
    
    public void setHomeTeamName(String homeTeamName) {
        this.homeTeamName = homeTeamName;
    }

    
    @Column(name="awayTeamName", length=100)
    public String getAwayTeamName() {
        return this.awayTeamName;
    }
    
    public void setAwayTeamName(String awayTeamName) {
        this.awayTeamName = awayTeamName;
    }




}


