package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeaguesCountry generated by hbm2java
 */
@Entity
@Table(name="leagues_country"
    ,catalog="footballsite"
)
public class LeaguesCountry  implements java.io.Serializable {


     private Integer recordId;
     private String countryName;
     private String countryCode;
     private Integer orderNo;
     private byte[] countryFlag;

    public LeaguesCountry() {
    }

    public LeaguesCountry(String countryName, String countryCode, Integer orderNo, byte[] countryFlag) {
       this.countryName = countryName;
       this.countryCode = countryCode;
       this.orderNo = orderNo;
       this.countryFlag = countryFlag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", unique=true, nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="country_name", length=100)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="country_code", length=100)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="order_no")
    public Integer getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    
    @Column(name="country_flag")
    public byte[] getCountryFlag() {
        return this.countryFlag;
    }
    
    public void setCountryFlag(byte[] countryFlag) {
        this.countryFlag = countryFlag;
    }




}


