package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Leagues generated by hbm2java
 */
@Entity
@Table(name = "leagues", catalog = "footballsite"
)
public class Leagues implements java.io.Serializable {

    private Integer recordId;
    private String caption;
    private String league;
    private Integer year;
    private Integer numberOfTeams;
    private Integer numberOfGames;
    private String selfLink;
    private Date lastUpdated;
    private Integer countryId;
    private Integer orderNo;
    private byte[] leagueIcon;

    public Leagues() {
    }

    public Leagues(String caption, String league, Integer year, Integer numberOfTeams, Integer numberOfGames, String selfLink, Date lastUpdated, Integer countryId, byte[] leagueIcon) {
        this.caption = caption;
        this.league = league;
        this.year = year;
        this.numberOfTeams = numberOfTeams;
        this.numberOfGames = numberOfGames;
        this.selfLink = selfLink;
        this.lastUpdated = lastUpdated;
        this.countryId = countryId;
        this.leagueIcon = leagueIcon;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "record_id", nullable = false)
    public Integer getRecordId() {
        return this.recordId;
    }

    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    @Column(name = "caption", length = 100)
    public String getCaption() {
        return this.caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    @Column(name = "league", length = 100)
    public String getLeague() {
        return this.league;
    }

    public void setLeague(String league) {
        this.league = league;
    }

    @Column(name = "year")
    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    @Column(name = "numberOfTeams")
    public Integer getNumberOfTeams() {
        return this.numberOfTeams;
    }

    public void setNumberOfTeams(Integer numberOfTeams) {
        this.numberOfTeams = numberOfTeams;
    }

    @Column(name = "numberOfGames")
    public Integer getNumberOfGames() {
        return this.numberOfGames;
    }

    public void setNumberOfGames(Integer numberOfGames) {
        this.numberOfGames = numberOfGames;
    }

    @Column(name = "self_link", length = 150)
    public String getSelfLink() {
        return this.selfLink;
    }

    public void setSelfLink(String selfLink) {
        this.selfLink = selfLink;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastUpdated", length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Column(name = "country_id")
    public Integer getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    @Column(name = "order_no")
    public Integer getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    @Column(name = "league_icon")
    public byte[] getLeagueIcon() {
        return this.leagueIcon;
    }

    public void setLeagueIcon(byte[] leagueIcon) {
        this.leagueIcon = leagueIcon;
    }

}
