package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeagueTableTeamStatistics generated by hbm2java
 */
@Entity
@Table(name="league_table_team_statistics"
    ,catalog="footballsite"
)
public class LeagueTableTeamStatistics  implements java.io.Serializable {


     private Integer recordId;
     private Integer leagueTableRowId;
     private String statisticOwn;
     private Integer goals;
     private Integer goalsAgainst;
     private Integer wins;
     private Integer draws;
     private Integer losses;

    public LeagueTableTeamStatistics() {
    }

    public LeagueTableTeamStatistics(Integer leagueTableRowId, String statisticOwn, Integer goals, Integer goalsAgainst, Integer wins, Integer draws, Integer losses) {
       this.leagueTableRowId = leagueTableRowId;
       this.statisticOwn = statisticOwn;
       this.goals = goals;
       this.goalsAgainst = goalsAgainst;
       this.wins = wins;
       this.draws = draws;
       this.losses = losses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="league_table_row_id")
    public Integer getLeagueTableRowId() {
        return this.leagueTableRowId;
    }
    
    public void setLeagueTableRowId(Integer leagueTableRowId) {
        this.leagueTableRowId = leagueTableRowId;
    }

    
    @Column(name="statistic_own", length=10)
    public String getStatisticOwn() {
        return this.statisticOwn;
    }
    
    public void setStatisticOwn(String statisticOwn) {
        this.statisticOwn = statisticOwn;
    }

    
    @Column(name="goals")
    public Integer getGoals() {
        return this.goals;
    }
    
    public void setGoals(Integer goals) {
        this.goals = goals;
    }

    
    @Column(name="goalsAgainst")
    public Integer getGoalsAgainst() {
        return this.goalsAgainst;
    }
    
    public void setGoalsAgainst(Integer goalsAgainst) {
        this.goalsAgainst = goalsAgainst;
    }

    
    @Column(name="wins")
    public Integer getWins() {
        return this.wins;
    }
    
    public void setWins(Integer wins) {
        this.wins = wins;
    }

    
    @Column(name="draws")
    public Integer getDraws() {
        return this.draws;
    }
    
    public void setDraws(Integer draws) {
        this.draws = draws;
    }

    
    @Column(name="losses")
    public Integer getLosses() {
        return this.losses;
    }
    
    public void setLosses(Integer losses) {
        this.losses = losses;
    }




}


