package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Players generated by hbm2java
 */
@Entity
@Table(name="players"
    ,catalog="footballsite"
)
public class Players  implements java.io.Serializable {


     private Integer recordId;
     private Integer teamsId;
     private String name;
     private String position;
     private Integer jerseyNumber;
     private Date dateOfBirth;
     private String nationality;
     private Date contractUntil;
     private String marketValue;
     private Double marketValueNumber;
     private String marketValueMoneyType;

    public Players() {
    }

    public Players(Integer teamsId, String name, String position, Integer jerseyNumber, Date dateOfBirth, String nationality, Date contractUntil, String marketValue, Double marketValueNumber, String marketValueMoneyType) {
       this.teamsId = teamsId;
       this.name = name;
       this.position = position;
       this.jerseyNumber = jerseyNumber;
       this.dateOfBirth = dateOfBirth;
       this.nationality = nationality;
       this.contractUntil = contractUntil;
       this.marketValue = marketValue;
       this.marketValueNumber = marketValueNumber;
       this.marketValueMoneyType = marketValueMoneyType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="teams_id")
    public Integer getTeamsId() {
        return this.teamsId;
    }
    
    public void setTeamsId(Integer teamsId) {
        this.teamsId = teamsId;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="position", length=45)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="jerseyNumber")
    public Integer getJerseyNumber() {
        return this.jerseyNumber;
    }
    
    public void setJerseyNumber(Integer jerseyNumber) {
        this.jerseyNumber = jerseyNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateOfBirth", length=19)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="nationality", length=100)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="contractUntil", length=19)
    public Date getContractUntil() {
        return this.contractUntil;
    }
    
    public void setContractUntil(Date contractUntil) {
        this.contractUntil = contractUntil;
    }

    
    @Column(name="marketValue", length=100)
    public String getMarketValue() {
        return this.marketValue;
    }
    
    public void setMarketValue(String marketValue) {
        this.marketValue = marketValue;
    }

    
    @Column(name="marketValueNumber", precision=20)
    public Double getMarketValueNumber() {
        return this.marketValueNumber;
    }
    
    public void setMarketValueNumber(Double marketValueNumber) {
        this.marketValueNumber = marketValueNumber;
    }

    
    @Column(name="marketValueMoneyType", length=45)
    public String getMarketValueMoneyType() {
        return this.marketValueMoneyType;
    }
    
    public void setMarketValueMoneyType(String marketValueMoneyType) {
        this.marketValueMoneyType = marketValueMoneyType;
    }




}


