package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teams generated by hbm2java
 */
@Entity
@Table(name="teams"
    ,catalog="footballsite"
)
public class Teams  implements java.io.Serializable {


     private Integer recordId;
     private Integer leagueId;
     private String name;
     private String code;
     private String shortName;
     private String crestUrl;
     private byte[] crestPicture;

    public Teams() {
    }

    public Teams(Integer leagueId, String name, String code, String shortName, String crestUrl, byte[] crestPicture) {
       this.leagueId = leagueId;
       this.name = name;
       this.code = code;
       this.shortName = shortName;
       this.crestUrl = crestUrl;
       this.crestPicture = crestPicture;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="league_id")
    public Integer getLeagueId() {
        return this.leagueId;
    }
    
    public void setLeagueId(Integer leagueId) {
        this.leagueId = leagueId;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="code", length=100)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="shortName", length=100)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    
    @Column(name="crestUrl", length=150)
    public String getCrestUrl() {
        return this.crestUrl;
    }
    
    public void setCrestUrl(String crestUrl) {
        this.crestUrl = crestUrl;
    }

    
    @Column(name="crestPicture")
    public byte[] getCrestPicture() {
        return this.crestPicture;
    }
    
    public void setCrestPicture(byte[] crestPicture) {
        this.crestPicture = crestPicture;
    }




}


