package com.football.site.entity;
// Generated Jan 3, 2016 2:08:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="user_info"
    ,catalog="footballsite"
)
public class UserInfo  implements java.io.Serializable {


     private Integer recordId;
     private String emailAddress;
     private String password;
     private String nameSurname;
     private String countryCode;
     private Integer teamId;
     private byte[] pictures;
     private Date createDate;
     private String recordStatus;

    public UserInfo() {
    }

    public UserInfo(String emailAddress, String password, String nameSurname, String countryCode, Integer teamId, byte[] pictures, Date createDate, String recordStatus) {
       this.emailAddress = emailAddress;
       this.password = password;
       this.nameSurname = nameSurname;
       this.countryCode = countryCode;
       this.teamId = teamId;
       this.pictures = pictures;
       this.createDate = createDate;
       this.recordStatus = recordStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    
    @Column(name="email_address", length=100)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name_surname", length=100)
    public String getNameSurname() {
        return this.nameSurname;
    }
    
    public void setNameSurname(String nameSurname) {
        this.nameSurname = nameSurname;
    }

    
    @Column(name="country_code", length=5)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="team_id")
    public Integer getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    
    @Column(name="pictures")
    public byte[] getPictures() {
        return this.pictures;
    }
    
    public void setPictures(byte[] pictures) {
        this.pictures = pictures;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="record_status", length=1)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }




}


